### ISSUE TITLE
[enhancement] Add the entire CVE "blob" to the JSON-export

### ISSUE THREAD

**Issue by p0dalirius** [p0dalirius/ApacheTomcatScanner#35]
> In theory, it might be useful to add the entire CVE "blob" to the JSON-export and leave further filtering to the user which uses it later, but I leave you to decide that. If you think that's a good idea, then I'll rework it towards that.

> Downside to that: the 3 exports would differ in that way.

_Originally posted by @Sandr0x00 in https://github.com/p0dalirius/ApacheTomcatScanner/issues/34#issuecomment-1734052828_
            

I think you are right, this is a good idea.

**Comment by Sandr0x00** [comment]
You'll get another PR tomorrow fixing that :)
