### ISSUE TITLE
[bug] Issue with expand_port_range

### ISSUE THREAD

**Issue by Plumatester** [p0dalirius/ApacheTomcatScanner#8]
After installing with setup.py and getting everything in requirements.txt with pip3, I still cannot run the scanner because of this import error:

Traceback (most recent call last):
  File "/root/tools/ApacheTomcatScanner-2.0/ApacheTomcatScanner.py", line 8, in <module>
    from apachetomcatscanner.__main__ import main
  File "/root/tools/ApacheTomcatScanner-2.0/apachetomcatscanner/__main__.py", line 16, in <module>
    from sectools.network.ip import is_ipv4_cidr, is_ipv4_addr, is_ipv6_addr, expand_cidr, expand_port_range
ImportError: cannot import name 'expand_port_range' from 'sectools.network.ip' (/root/tools/ApacheTomcatScanner-2.0/venv/lib/python3.9/site-packages/sectools-1.2-py3.9.egg/sectools/network/ip.py)

**Comment by p0dalirius** [comment]
Hey,

Thanks for your issue,

I found out your problem, I forgot to publish sectools==1.3 on PyPi, therefore it did work on my machine, but not on others. I just released the sectools 1.3 everything should work now. 
 
 - https://github.com/p0dalirius/sectools/releases/tag/1.3
 - https://pypi.org/project/sectools/1.3/

Best regards

**Comment by p0dalirius** [comment]
Fixed
